categories:
  - title: 🚀 Enhancement
    labels:
      - 'enhancement'
  - title: 🐞 Bug fixes
    labels:
      - 'bugfix'
      - 'bug'
  - title: 🍀 Environment
    labels:
      - 'env'
  - title: 📝 Documentation
    labels:
      - 'documentation'
  - title: 🧩 Others

exclude-labels:
  - 'skip-changelog'
publish: 'true'

change-template: '- $TITLE by @$AUTHOR in (#$NUMBER)'
no-changes-template: '- No changes'

template: |
  ## What's Changed

  $CHANGES
