name-template: 'Release $RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'

categories:
  - title: 🚀 Features
    labels:
      - 'enhancement'
  - title: 🐛 Bug Fixes
    labels:
      - 'bugfix'
      - 'bug'
  - title: 🧩 Others
    labels:
      - other

change-template: '- $TITLE by @$AUTHOR in (#$NUMBER)'
no-changes-template: '- No changes'

template: |
  ## What's Changed

  $CHANGES
