name-template: 'Release ${{ tag_name }}'
tag-template: '${{ tag_name }}'

categories:
  - title: 🚀 Features
    labels:
      - 'enhancement'
  - title: 🐛 Bug Fixes
    labels:
      - 'bugfix'
  - title: 🧩 Others
    labels:
      - other

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
no-changes-template: '- No changes'

template: |
  ## Changes

  $CHANGES
