name: invalid

on:
  push:
    tags:
      - 'v*' # vで始まるタグ

jobs:
  draft-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
          
      - name: Generate Release Notes
        uses: release-drafter/release-drafter@v6
        with:
            tag: ${{ github.ref_name }}
            name: ${{ github.ref_name }}
            version: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
