name: Release Git-tag of poetry-managed package

on:
  pull_request:
    branches: 
      - main
    types:
      - closed

jobs:
  release:
    if: >
        github.event.pull_request.merged == true || 
        github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 1
      
      # Made use of $GITHUB_ENV to pass the variable cleanly to subsequent steps.
      - name: Fetch version info from pyproject.toml
        run: |
          echo "PYPROJECT_VERSION=5.2" >> $GITHUB_ENV
          echo "The current pyproject version is v$PYPROJECT_VERSION"

      
      - name: Create Git Tag
        id: tag
        run: |
          TAG=$(git describe HEAD --tags --abbrev=0 2>/dev/null || echo "none")

          if [[ "$TAG" != "v$PYPROJECT_VERSION" ]]; then
            echo "Creating a new release with tag v$PYPROJECT_VERSION..."
            echo "RELEASE_TAG=$PYPROJECT_VERSION" >> $GITHUB_ENV
          else
            echo "Tag v$PYPROJECT_VERSION already exists. No release needed."
          fi
          
        env:
          GH_TOKEN: ${{ github.token }}

      # run only if new tag should be created
      - name: Generate Release Notes
        if: ${{ env.RELEASE_TAG != ''}}
        uses: release-drafter/release-drafter@v6
        with:
            tag: v${{ env.RELEASE_TAG }}
            name: v${{ env.RELEASE_TAG }}
            version: ${{ env.RELEASE_TAG }}
            publish: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
